// <auto-generated />
using System;
using DeliCode.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeliCode.ProductAPI.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20201215131318_SeedDb")]
    partial class SeedDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DeliCode.ProductAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountInStorage")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("891ceb12-e067-4596-a8a2-4e0a4b9eef6e"),
                            AmountInStorage = 3,
                            Description = "Varma",
                            ImageUrl = "https://picsum.photos/id/133/286/180",
                            Name = "Kanelbulle",
                            Price = 9.50m
                        },
                        new
                        {
                            Id = new Guid("bd8f361d-e5e3-4f33-82cf-2594368d78c3"),
                            AmountInStorage = 0,
                            Description = "Extra florsocker",
                            ImageUrl = "https://picsum.photos/id/106/286/180",
                            Name = "Kladdkarta",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = new Guid("4df795cf-ea1c-47c1-a4e0-f20742cfe359"),
                            AmountInStorage = 3,
                            Description = "Innehåller grädde",
                            ImageUrl = "https://picsum.photos/id/292/286/180",
                            Name = "Tårta",
                            Price = 79.90m
                        },
                        new
                        {
                            Id = new Guid("7ec6222e-32d6-4293-8d23-85504851156c"),
                            AmountInStorage = 1,
                            Description = "En vanlig cheesecake",
                            ImageUrl = "https://picsum.photos/id/104/286/180",
                            Name = "Cheesecake",
                            Price = 29.90m
                        },
                        new
                        {
                            Id = new Guid("c64c3fc5-3e3f-4c5a-9baf-e0e58541ab07"),
                            AmountInStorage = 4,
                            Description = "Stora",
                            ImageUrl = "https://picsum.photos/id/143/286/180",
                            Name = "Muffin",
                            Price = 19.90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
